version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.5-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      - image: circleci/postgres:9.6.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v '2.1.4'
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            sudo apt update
            sudo apt install postgresql-client
            sudo npm install -g mjml@4.3.1
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Run rubocop
          command: bin/rubocop

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
  deploy:
    docker:
      - image: circleci/ruby:2.5.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install dpl
      - run:
          name: Deploy
          command: |
            dpl --provider=heroku --app=spotcodev2 --api-key=$HEROKU_API_KEY
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: org-global
          filters:
            branches:
              only: master